import Head from 'next/head'
import Image from 'next/image'
import { Controller, useForm } from "react-hook-form";
import { Button, Form, Input } from "antd";

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { TableExample } from './TableExample';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [loading, setLoading] = useState(false)
  const [showTable, setShowTable] = useState("none")
  const {
    control: control,
    handleSubmit: matSubmit,
    formState: { errors: matErrors },
  } = useForm();

  const handleFormSubmit = (data:string) => {
    // setLoading(!loading);
    showTable === "none" ? setShowTable("block") : setShowTable("none");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <Form
    name="basic"
    labelCol={{ span: 8 }}
    wrapperCol={{ span: 16 }}
    style={{ maxWidth: 600 }}
    initialValues={{ remember: true }}
    onFinish={handleFormSubmit}
    autoComplete="off"
  >
    <Form.Item
      label="Username"
      name="username"
      rules={[{ required: true, message: 'Please input your username!' }]}
    >
      <Input />
    </Form.Item>
    <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
      <Button type="primary" htmlType="submit">
        Submit
      </Button>
    </Form.Item>
  </Form>
  <div style={{display:`${showTable}`}}>
    <TableExample/>

  </div>
      </main>
    </>
  )
}
